//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap11Binding", Namespace="http://ws.apache.org/axis2")]
public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback exportSaFetchDataOperationCompleted;
    
    private System.Threading.SendOrPostCallback gensabackdtlOperationCompleted;
    
    private System.Threading.SendOrPostCallback exportSaDataOperationCompleted;
    
    private System.Threading.SendOrPostCallback mainOperationCompleted;
    
    private System.Threading.SendOrPostCallback exportWuliucosDataOperationCompleted;
    
    private System.Threading.SendOrPostCallback exportCustomersDataOperationCompleted;
    
    private System.Threading.SendOrPostCallback doSaFetchKeepinOperationCompleted;
    
    private System.Threading.SendOrPostCallback exportStorageDefsDataOperationCompleted;
    
    private System.Threading.SendOrPostCallback doMoveoutOperationCompleted;
    
    private System.Threading.SendOrPostCallback exportCompanysDataOperationCompleted;
    
    private System.Threading.SendOrPostCallback doSaKeepinOperationCompleted;
    
    private System.Threading.SendOrPostCallback exportEmployeesDataOperationCompleted;
    
    private System.Threading.SendOrPostCallback exportDicDataOperationCompleted;
    
    private System.Threading.SendOrPostCallback exportPosDefsDataOperationCompleted;
    
    private System.Threading.SendOrPostCallback doMoveinOperationCompleted;
    
    /// <remarks/>
    public WebService() {
        this.Url = "http://192.168.0.213:8080/axis2/services/WebService.WebServiceHttpSoap11Endpoint/" +
            "";
    }
    
    /// <remarks/>
    public event exportSaFetchDataCompletedEventHandler exportSaFetchDataCompleted;
    
    /// <remarks/>
    public event gensabackdtlCompletedEventHandler gensabackdtlCompleted;
    
    /// <remarks/>
    public event exportSaDataCompletedEventHandler exportSaDataCompleted;
    
    /// <remarks/>
    public event mainCompletedEventHandler mainCompleted;
    
    /// <remarks/>
    public event exportWuliucosDataCompletedEventHandler exportWuliucosDataCompleted;
    
    /// <remarks/>
    public event exportCustomersDataCompletedEventHandler exportCustomersDataCompleted;
    
    /// <remarks/>
    public event doSaFetchKeepinCompletedEventHandler doSaFetchKeepinCompleted;
    
    /// <remarks/>
    public event exportStorageDefsDataCompletedEventHandler exportStorageDefsDataCompleted;
    
    /// <remarks/>
    public event doMoveoutCompletedEventHandler doMoveoutCompleted;
    
    /// <remarks/>
    public event exportCompanysDataCompletedEventHandler exportCompanysDataCompleted;
    
    /// <remarks/>
    public event doSaKeepinCompletedEventHandler doSaKeepinCompleted;
    
    /// <remarks/>
    public event exportEmployeesDataCompletedEventHandler exportEmployeesDataCompleted;
    
    /// <remarks/>
    public event exportDicDataCompletedEventHandler exportDicDataCompleted;
    
    /// <remarks/>
    public event exportPosDefsDataCompletedEventHandler exportPosDefsDataCompleted;
    
    /// <remarks/>
    public event doMoveinCompletedEventHandler doMoveinCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:exportSaFetchData", RequestNamespace="http://ws.apache.org/axis2", ResponseNamespace="http://ws.apache.org/axis2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string exportSaFetchData([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string args0) {
        object[] results = this.Invoke("exportSaFetchData", new object[] {
                    args0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginexportSaFetchData(string args0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("exportSaFetchData", new object[] {
                    args0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndexportSaFetchData(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void exportSaFetchDataAsync(string args0) {
        this.exportSaFetchDataAsync(args0, null);
    }
    
    /// <remarks/>
    public void exportSaFetchDataAsync(string args0, object userState) {
        if ((this.exportSaFetchDataOperationCompleted == null)) {
            this.exportSaFetchDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexportSaFetchDataOperationCompleted);
        }
        this.InvokeAsync("exportSaFetchData", new object[] {
                    args0}, this.exportSaFetchDataOperationCompleted, userState);
    }
    
    private void OnexportSaFetchDataOperationCompleted(object arg) {
        if ((this.exportSaFetchDataCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.exportSaFetchDataCompleted(this, new exportSaFetchDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:gensabackdtl", RequestNamespace="http://ws.apache.org/axis2", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void gensabackdtl([System.Xml.Serialization.XmlElementAttribute("args0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int[] args0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] DBTableModel args1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] DBTableModel args2) {
        this.Invoke("gensabackdtl", new object[] {
                    args0,
                    args1,
                    args2});
    }
    
    /// <remarks/>
    public System.IAsyncResult Begingensabackdtl(int[] args0, DBTableModel args1, DBTableModel args2, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("gensabackdtl", new object[] {
                    args0,
                    args1,
                    args2}, callback, asyncState);
    }
    
    /// <remarks/>
    public void Endgensabackdtl(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void gensabackdtlAsync(int[] args0, DBTableModel args1, DBTableModel args2) {
        this.gensabackdtlAsync(args0, args1, args2, null);
    }
    
    /// <remarks/>
    public void gensabackdtlAsync(int[] args0, DBTableModel args1, DBTableModel args2, object userState) {
        if ((this.gensabackdtlOperationCompleted == null)) {
            this.gensabackdtlOperationCompleted = new System.Threading.SendOrPostCallback(this.OngensabackdtlOperationCompleted);
        }
        this.InvokeAsync("gensabackdtl", new object[] {
                    args0,
                    args1,
                    args2}, this.gensabackdtlOperationCompleted, userState);
    }
    
    private void OngensabackdtlOperationCompleted(object arg) {
        if ((this.gensabackdtlCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.gensabackdtlCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:exportSaData", RequestNamespace="http://ws.apache.org/axis2", ResponseNamespace="http://ws.apache.org/axis2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string exportSaData([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string args0) {
        object[] results = this.Invoke("exportSaData", new object[] {
                    args0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginexportSaData(string args0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("exportSaData", new object[] {
                    args0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndexportSaData(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void exportSaDataAsync(string args0) {
        this.exportSaDataAsync(args0, null);
    }
    
    /// <remarks/>
    public void exportSaDataAsync(string args0, object userState) {
        if ((this.exportSaDataOperationCompleted == null)) {
            this.exportSaDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexportSaDataOperationCompleted);
        }
        this.InvokeAsync("exportSaData", new object[] {
                    args0}, this.exportSaDataOperationCompleted, userState);
    }
    
    private void OnexportSaDataOperationCompleted(object arg) {
        if ((this.exportSaDataCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.exportSaDataCompleted(this, new exportSaDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:main", RequestNamespace="http://ws.apache.org/axis2", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void main([System.Xml.Serialization.XmlElementAttribute("args0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] args0) {
        this.Invoke("main", new object[] {
                    args0});
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginmain(string[] args0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("main", new object[] {
                    args0}, callback, asyncState);
    }
    
    /// <remarks/>
    public void Endmain(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void mainAsync(string[] args0) {
        this.mainAsync(args0, null);
    }
    
    /// <remarks/>
    public void mainAsync(string[] args0, object userState) {
        if ((this.mainOperationCompleted == null)) {
            this.mainOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmainOperationCompleted);
        }
        this.InvokeAsync("main", new object[] {
                    args0}, this.mainOperationCompleted, userState);
    }
    
    private void OnmainOperationCompleted(object arg) {
        if ((this.mainCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.mainCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:exportWuliucosData", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("exportWuliucosDataResponse", Namespace="http://ws.apache.org/axis2")]
    public exportWuliucosDataResponse exportWuliucosData() {
        object[] results = this.Invoke("exportWuliucosData", new object[0]);
        return ((exportWuliucosDataResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginexportWuliucosData(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("exportWuliucosData", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public exportWuliucosDataResponse EndexportWuliucosData(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((exportWuliucosDataResponse)(results[0]));
    }
    
    /// <remarks/>
    public void exportWuliucosDataAsync() {
        this.exportWuliucosDataAsync(null);
    }
    
    /// <remarks/>
    public void exportWuliucosDataAsync(object userState) {
        if ((this.exportWuliucosDataOperationCompleted == null)) {
            this.exportWuliucosDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexportWuliucosDataOperationCompleted);
        }
        this.InvokeAsync("exportWuliucosData", new object[0], this.exportWuliucosDataOperationCompleted, userState);
    }
    
    private void OnexportWuliucosDataOperationCompleted(object arg) {
        if ((this.exportWuliucosDataCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.exportWuliucosDataCompleted(this, new exportWuliucosDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:exportCustomersData", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("exportCustomersDataResponse", Namespace="http://ws.apache.org/axis2")]
    public exportCustomersDataResponse exportCustomersData() {
        object[] results = this.Invoke("exportCustomersData", new object[0]);
        return ((exportCustomersDataResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginexportCustomersData(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("exportCustomersData", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public exportCustomersDataResponse EndexportCustomersData(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((exportCustomersDataResponse)(results[0]));
    }
    
    /// <remarks/>
    public void exportCustomersDataAsync() {
        this.exportCustomersDataAsync(null);
    }
    
    /// <remarks/>
    public void exportCustomersDataAsync(object userState) {
        if ((this.exportCustomersDataOperationCompleted == null)) {
            this.exportCustomersDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexportCustomersDataOperationCompleted);
        }
        this.InvokeAsync("exportCustomersData", new object[0], this.exportCustomersDataOperationCompleted, userState);
    }
    
    private void OnexportCustomersDataOperationCompleted(object arg) {
        if ((this.exportCustomersDataCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.exportCustomersDataCompleted(this, new exportCustomersDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:doSaFetchKeepin", RequestNamespace="http://ws.apache.org/axis2", ResponseNamespace="http://ws.apache.org/axis2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string doSaFetchKeepin([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string args0) {
        object[] results = this.Invoke("doSaFetchKeepin", new object[] {
                    args0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindoSaFetchKeepin(string args0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("doSaFetchKeepin", new object[] {
                    args0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EnddoSaFetchKeepin(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void doSaFetchKeepinAsync(string args0) {
        this.doSaFetchKeepinAsync(args0, null);
    }
    
    /// <remarks/>
    public void doSaFetchKeepinAsync(string args0, object userState) {
        if ((this.doSaFetchKeepinOperationCompleted == null)) {
            this.doSaFetchKeepinOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoSaFetchKeepinOperationCompleted);
        }
        this.InvokeAsync("doSaFetchKeepin", new object[] {
                    args0}, this.doSaFetchKeepinOperationCompleted, userState);
    }
    
    private void OndoSaFetchKeepinOperationCompleted(object arg) {
        if ((this.doSaFetchKeepinCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.doSaFetchKeepinCompleted(this, new doSaFetchKeepinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:exportStorageDefsData", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("exportStorageDefsDataResponse", Namespace="http://ws.apache.org/axis2")]
    public exportStorageDefsDataResponse exportStorageDefsData() {
        object[] results = this.Invoke("exportStorageDefsData", new object[0]);
        return ((exportStorageDefsDataResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginexportStorageDefsData(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("exportStorageDefsData", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public exportStorageDefsDataResponse EndexportStorageDefsData(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((exportStorageDefsDataResponse)(results[0]));
    }
    
    /// <remarks/>
    public void exportStorageDefsDataAsync() {
        this.exportStorageDefsDataAsync(null);
    }
    
    /// <remarks/>
    public void exportStorageDefsDataAsync(object userState) {
        if ((this.exportStorageDefsDataOperationCompleted == null)) {
            this.exportStorageDefsDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexportStorageDefsDataOperationCompleted);
        }
        this.InvokeAsync("exportStorageDefsData", new object[0], this.exportStorageDefsDataOperationCompleted, userState);
    }
    
    private void OnexportStorageDefsDataOperationCompleted(object arg) {
        if ((this.exportStorageDefsDataCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.exportStorageDefsDataCompleted(this, new exportStorageDefsDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:doMoveout", RequestNamespace="http://ws.apache.org/axis2", ResponseNamespace="http://ws.apache.org/axis2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string doMoveout([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string args0) {
        object[] results = this.Invoke("doMoveout", new object[] {
                    args0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindoMoveout(string args0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("doMoveout", new object[] {
                    args0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EnddoMoveout(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void doMoveoutAsync(string args0) {
        this.doMoveoutAsync(args0, null);
    }
    
    /// <remarks/>
    public void doMoveoutAsync(string args0, object userState) {
        if ((this.doMoveoutOperationCompleted == null)) {
            this.doMoveoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoMoveoutOperationCompleted);
        }
        this.InvokeAsync("doMoveout", new object[] {
                    args0}, this.doMoveoutOperationCompleted, userState);
    }
    
    private void OndoMoveoutOperationCompleted(object arg) {
        if ((this.doMoveoutCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.doMoveoutCompleted(this, new doMoveoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:exportCompanysData", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("exportCompanysDataResponse", Namespace="http://ws.apache.org/axis2")]
    public exportCompanysDataResponse exportCompanysData() {
        object[] results = this.Invoke("exportCompanysData", new object[0]);
        return ((exportCompanysDataResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginexportCompanysData(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("exportCompanysData", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public exportCompanysDataResponse EndexportCompanysData(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((exportCompanysDataResponse)(results[0]));
    }
    
    /// <remarks/>
    public void exportCompanysDataAsync() {
        this.exportCompanysDataAsync(null);
    }
    
    /// <remarks/>
    public void exportCompanysDataAsync(object userState) {
        if ((this.exportCompanysDataOperationCompleted == null)) {
            this.exportCompanysDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexportCompanysDataOperationCompleted);
        }
        this.InvokeAsync("exportCompanysData", new object[0], this.exportCompanysDataOperationCompleted, userState);
    }
    
    private void OnexportCompanysDataOperationCompleted(object arg) {
        if ((this.exportCompanysDataCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.exportCompanysDataCompleted(this, new exportCompanysDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:doSaKeepin", RequestNamespace="http://ws.apache.org/axis2", ResponseNamespace="http://ws.apache.org/axis2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string doSaKeepin([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string args0) {
        object[] results = this.Invoke("doSaKeepin", new object[] {
                    args0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindoSaKeepin(string args0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("doSaKeepin", new object[] {
                    args0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EnddoSaKeepin(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void doSaKeepinAsync(string args0) {
        this.doSaKeepinAsync(args0, null);
    }
    
    /// <remarks/>
    public void doSaKeepinAsync(string args0, object userState) {
        if ((this.doSaKeepinOperationCompleted == null)) {
            this.doSaKeepinOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoSaKeepinOperationCompleted);
        }
        this.InvokeAsync("doSaKeepin", new object[] {
                    args0}, this.doSaKeepinOperationCompleted, userState);
    }
    
    private void OndoSaKeepinOperationCompleted(object arg) {
        if ((this.doSaKeepinCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.doSaKeepinCompleted(this, new doSaKeepinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:exportEmployeesData", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("exportEmployeesDataResponse", Namespace="http://ws.apache.org/axis2")]
    public exportEmployeesDataResponse exportEmployeesData() {
        object[] results = this.Invoke("exportEmployeesData", new object[0]);
        return ((exportEmployeesDataResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginexportEmployeesData(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("exportEmployeesData", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public exportEmployeesDataResponse EndexportEmployeesData(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((exportEmployeesDataResponse)(results[0]));
    }
    
    /// <remarks/>
    public void exportEmployeesDataAsync() {
        this.exportEmployeesDataAsync(null);
    }
    
    /// <remarks/>
    public void exportEmployeesDataAsync(object userState) {
        if ((this.exportEmployeesDataOperationCompleted == null)) {
            this.exportEmployeesDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexportEmployeesDataOperationCompleted);
        }
        this.InvokeAsync("exportEmployeesData", new object[0], this.exportEmployeesDataOperationCompleted, userState);
    }
    
    private void OnexportEmployeesDataOperationCompleted(object arg) {
        if ((this.exportEmployeesDataCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.exportEmployeesDataCompleted(this, new exportEmployeesDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:exportDicData", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("exportDicDataResponse", Namespace="http://ws.apache.org/axis2")]
    public exportDicDataResponse exportDicData() {
        object[] results = this.Invoke("exportDicData", new object[0]);
        return ((exportDicDataResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginexportDicData(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("exportDicData", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public exportDicDataResponse EndexportDicData(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((exportDicDataResponse)(results[0]));
    }
    
    /// <remarks/>
    public void exportDicDataAsync() {
        this.exportDicDataAsync(null);
    }
    
    /// <remarks/>
    public void exportDicDataAsync(object userState) {
        if ((this.exportDicDataOperationCompleted == null)) {
            this.exportDicDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexportDicDataOperationCompleted);
        }
        this.InvokeAsync("exportDicData", new object[0], this.exportDicDataOperationCompleted, userState);
    }
    
    private void OnexportDicDataOperationCompleted(object arg) {
        if ((this.exportDicDataCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.exportDicDataCompleted(this, new exportDicDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:exportPosDefsData", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("exportPosDefsDataResponse", Namespace="http://ws.apache.org/axis2")]
    public exportPosDefsDataResponse exportPosDefsData() {
        object[] results = this.Invoke("exportPosDefsData", new object[0]);
        return ((exportPosDefsDataResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginexportPosDefsData(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("exportPosDefsData", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public exportPosDefsDataResponse EndexportPosDefsData(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((exportPosDefsDataResponse)(results[0]));
    }
    
    /// <remarks/>
    public void exportPosDefsDataAsync() {
        this.exportPosDefsDataAsync(null);
    }
    
    /// <remarks/>
    public void exportPosDefsDataAsync(object userState) {
        if ((this.exportPosDefsDataOperationCompleted == null)) {
            this.exportPosDefsDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexportPosDefsDataOperationCompleted);
        }
        this.InvokeAsync("exportPosDefsData", new object[0], this.exportPosDefsDataOperationCompleted, userState);
    }
    
    private void OnexportPosDefsDataOperationCompleted(object arg) {
        if ((this.exportPosDefsDataCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.exportPosDefsDataCompleted(this, new exportPosDefsDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:doMovein", RequestNamespace="http://ws.apache.org/axis2", ResponseNamespace="http://ws.apache.org/axis2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string doMovein([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string args0) {
        object[] results = this.Invoke("doMovein", new object[] {
                    args0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindoMovein(string args0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("doMovein", new object[] {
                    args0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EnddoMovein(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void doMoveinAsync(string args0) {
        this.doMoveinAsync(args0, null);
    }
    
    /// <remarks/>
    public void doMoveinAsync(string args0, object userState) {
        if ((this.doMoveinOperationCompleted == null)) {
            this.doMoveinOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoMoveinOperationCompleted);
        }
        this.InvokeAsync("doMovein", new object[] {
                    args0}, this.doMoveinOperationCompleted, userState);
    }
    
    private void OndoMoveinOperationCompleted(object arg) {
        if ((this.doMoveinCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.doMoveinCompleted(this, new doMoveinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://control.gui.np.inca.com/xsd")]
public partial class DBTableModel {
    
    private int columnCountField;
    
    private bool columnCountFieldSpecified;
    
    private bool crosstableField;
    
    private bool crosstableFieldSpecified;
    
    private object displaycolumninfosField;
    
    private bool fixtablecolumnwidthField;
    
    private bool fixtablecolumnwidthFieldSpecified;
    
    private bool hasmoreField;
    
    private bool hasmoreFieldSpecified;
    
    private bool isqueryingField;
    
    private bool isqueryingFieldSpecified;
    
    private RecordTrunk lineresultField;
    
    private object lineresultsField;
    
    private DBTableModel modifiedDataField;
    
    private string pkcolnameField;
    
    private bool queryingField;
    
    private bool queryingFieldSpecified;
    
    private DBTableModelEvent retrievelistenerField;
    
    private int rowCountField;
    
    private bool rowCountFieldSpecified;
    
    private string selectCMDField;
    
    private bool usequerythreadField;
    
    private bool usequerythreadFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int columnCount {
        get {
            return this.columnCountField;
        }
        set {
            this.columnCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool columnCountSpecified {
        get {
            return this.columnCountFieldSpecified;
        }
        set {
            this.columnCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool crosstable {
        get {
            return this.crosstableField;
        }
        set {
            this.crosstableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool crosstableSpecified {
        get {
            return this.crosstableFieldSpecified;
        }
        set {
            this.crosstableFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public object displaycolumninfos {
        get {
            return this.displaycolumninfosField;
        }
        set {
            this.displaycolumninfosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool fixtablecolumnwidth {
        get {
            return this.fixtablecolumnwidthField;
        }
        set {
            this.fixtablecolumnwidthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fixtablecolumnwidthSpecified {
        get {
            return this.fixtablecolumnwidthFieldSpecified;
        }
        set {
            this.fixtablecolumnwidthFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool hasmore {
        get {
            return this.hasmoreField;
        }
        set {
            this.hasmoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool hasmoreSpecified {
        get {
            return this.hasmoreFieldSpecified;
        }
        set {
            this.hasmoreFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool isquerying {
        get {
            return this.isqueryingField;
        }
        set {
            this.isqueryingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isqueryingSpecified {
        get {
            return this.isqueryingFieldSpecified;
        }
        set {
            this.isqueryingFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public RecordTrunk lineresult {
        get {
            return this.lineresultField;
        }
        set {
            this.lineresultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public object lineresults {
        get {
            return this.lineresultsField;
        }
        set {
            this.lineresultsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public DBTableModel modifiedData {
        get {
            return this.modifiedDataField;
        }
        set {
            this.modifiedDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string pkcolname {
        get {
            return this.pkcolnameField;
        }
        set {
            this.pkcolnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool querying {
        get {
            return this.queryingField;
        }
        set {
            this.queryingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool queryingSpecified {
        get {
            return this.queryingFieldSpecified;
        }
        set {
            this.queryingFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public DBTableModelEvent retrievelistener {
        get {
            return this.retrievelistenerField;
        }
        set {
            this.retrievelistenerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int rowCount {
        get {
            return this.rowCountField;
        }
        set {
            this.rowCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool rowCountSpecified {
        get {
            return this.rowCountFieldSpecified;
        }
        set {
            this.rowCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string selectCMD {
        get {
            return this.selectCMDField;
        }
        set {
            this.selectCMDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool usequerythread {
        get {
            return this.usequerythreadField;
        }
        set {
            this.usequerythreadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool usequerythreadSpecified {
        get {
            return this.usequerythreadFieldSpecified;
        }
        set {
            this.usequerythreadFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://communicate.np.inca.com/xsd")]
public partial class RecordTrunk {
    
    private object dbValuesField;
    
    private int dbdeletedField;
    
    private bool dbdeletedFieldSpecified;
    
    private int dbstatusField;
    
    private bool dbstatusFieldSpecified;
    
    private DBTableModel filedbmodelField;
    
    private int grouplevelField;
    
    private bool grouplevelFieldSpecified;
    
    private string groupnameField;
    
    private string relatevalueField;
    
    private string savemessageField;
    
    private int saveresultField;
    
    private bool saveresultFieldSpecified;
    
    private int sumflagField;
    
    private bool sumflagFieldSpecified;
    
    private string tmppkidField;
    
    private object wantuploadfileField;
    
    private object wantuploadfilesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public object dbValues {
        get {
            return this.dbValuesField;
        }
        set {
            this.dbValuesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int dbdeleted {
        get {
            return this.dbdeletedField;
        }
        set {
            this.dbdeletedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dbdeletedSpecified {
        get {
            return this.dbdeletedFieldSpecified;
        }
        set {
            this.dbdeletedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int dbstatus {
        get {
            return this.dbstatusField;
        }
        set {
            this.dbstatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dbstatusSpecified {
        get {
            return this.dbstatusFieldSpecified;
        }
        set {
            this.dbstatusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public DBTableModel filedbmodel {
        get {
            return this.filedbmodelField;
        }
        set {
            this.filedbmodelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int grouplevel {
        get {
            return this.grouplevelField;
        }
        set {
            this.grouplevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool grouplevelSpecified {
        get {
            return this.grouplevelFieldSpecified;
        }
        set {
            this.grouplevelFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string groupname {
        get {
            return this.groupnameField;
        }
        set {
            this.groupnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string relatevalue {
        get {
            return this.relatevalueField;
        }
        set {
            this.relatevalueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string savemessage {
        get {
            return this.savemessageField;
        }
        set {
            this.savemessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int saveresult {
        get {
            return this.saveresultField;
        }
        set {
            this.saveresultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool saveresultSpecified {
        get {
            return this.saveresultFieldSpecified;
        }
        set {
            this.saveresultFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int sumflag {
        get {
            return this.sumflagField;
        }
        set {
            this.sumflagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sumflagSpecified {
        get {
            return this.sumflagFieldSpecified;
        }
        set {
            this.sumflagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string tmppkid {
        get {
            return this.tmppkidField;
        }
        set {
            this.tmppkidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public object wantuploadfile {
        get {
            return this.wantuploadfileField;
        }
        set {
            this.wantuploadfileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public object wantuploadfiles {
        get {
            return this.wantuploadfilesField;
        }
        set {
            this.wantuploadfilesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://control.gui.np.inca.com/xsd")]
public partial class DBTableModelEvent {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.apache.org/axis2")]
public partial class exportWuliucosDataResponse {
    
    private string returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.apache.org/axis2")]
public partial class exportCustomersDataResponse {
    
    private string returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.apache.org/axis2")]
public partial class exportStorageDefsDataResponse {
    
    private string returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.apache.org/axis2")]
public partial class exportCompanysDataResponse {
    
    private string returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.apache.org/axis2")]
public partial class exportEmployeesDataResponse {
    
    private string returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.apache.org/axis2")]
public partial class exportDicDataResponse {
    
    private string returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.apache.org/axis2")]
public partial class exportPosDefsDataResponse {
    
    private string returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void exportSaFetchDataCompletedEventHandler(object sender, exportSaFetchDataCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class exportSaFetchDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal exportSaFetchDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void gensabackdtlCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void exportSaDataCompletedEventHandler(object sender, exportSaDataCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class exportSaDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal exportSaDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void mainCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void exportWuliucosDataCompletedEventHandler(object sender, exportWuliucosDataCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class exportWuliucosDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal exportWuliucosDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public exportWuliucosDataResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((exportWuliucosDataResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void exportCustomersDataCompletedEventHandler(object sender, exportCustomersDataCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class exportCustomersDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal exportCustomersDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public exportCustomersDataResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((exportCustomersDataResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void doSaFetchKeepinCompletedEventHandler(object sender, doSaFetchKeepinCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class doSaFetchKeepinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal doSaFetchKeepinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void exportStorageDefsDataCompletedEventHandler(object sender, exportStorageDefsDataCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class exportStorageDefsDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal exportStorageDefsDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public exportStorageDefsDataResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((exportStorageDefsDataResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void doMoveoutCompletedEventHandler(object sender, doMoveoutCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class doMoveoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal doMoveoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void exportCompanysDataCompletedEventHandler(object sender, exportCompanysDataCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class exportCompanysDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal exportCompanysDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public exportCompanysDataResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((exportCompanysDataResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void doSaKeepinCompletedEventHandler(object sender, doSaKeepinCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class doSaKeepinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal doSaKeepinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void exportEmployeesDataCompletedEventHandler(object sender, exportEmployeesDataCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class exportEmployeesDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal exportEmployeesDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public exportEmployeesDataResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((exportEmployeesDataResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void exportDicDataCompletedEventHandler(object sender, exportDicDataCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class exportDicDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal exportDicDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public exportDicDataResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((exportDicDataResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void exportPosDefsDataCompletedEventHandler(object sender, exportPosDefsDataCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class exportPosDefsDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal exportPosDefsDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public exportPosDefsDataResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((exportPosDefsDataResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void doMoveinCompletedEventHandler(object sender, doMoveinCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class doMoveinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal doMoveinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
