//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="WSBaseResServerFacadeSoapBinding", Namespace="http://218.76.35.178:7112/ormrpc/services/WSBaseResServerFacade")]
public partial class WSBaseResServerFacadeSrvProxyService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback queryBaseResOperationCompleted;
    
    /// <remarks/>
    public WSBaseResServerFacadeSrvProxyService() {
        this.Url = "http://218.76.35.178:7112//ormrpc/services/WSBaseResServerFacade";
    }
    
    /// <remarks/>
    public event queryBaseResCompletedEventHandler queryBaseResCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://webservice.webservice.custom.eas.kingdee.com", ResponseNamespace="http://218.76.35.178:7112/ormrpc/services/WSBaseResServerFacade")]
    [return: System.Xml.Serialization.SoapElementAttribute("queryBaseResReturn")]
    public string queryBaseRes(string resName, string queryParams) {
        object[] results = this.Invoke("queryBaseRes", new object[] {
                    resName,
                    queryParams});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginqueryBaseRes(string resName, string queryParams, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("queryBaseRes", new object[] {
                    resName,
                    queryParams}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndqueryBaseRes(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void queryBaseResAsync(string resName, string queryParams) {
        this.queryBaseResAsync(resName, queryParams, null);
    }
    
    /// <remarks/>
    public void queryBaseResAsync(string resName, string queryParams, object userState) {
        if ((this.queryBaseResOperationCompleted == null)) {
            this.queryBaseResOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryBaseResOperationCompleted);
        }
        this.InvokeAsync("queryBaseRes", new object[] {
                    resName,
                    queryParams}, this.queryBaseResOperationCompleted, userState);
    }
    
    private void OnqueryBaseResOperationCompleted(object arg) {
        if ((this.queryBaseResCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.queryBaseResCompleted(this, new queryBaseResCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void queryBaseResCompletedEventHandler(object sender, queryBaseResCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class queryBaseResCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal queryBaseResCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
