//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEasWindowsFormsApplication.IncServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.apache.org/axis2", ConfigurationName="IncServiceReference.WebServicePortType")]
    public interface WebServicePortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportSaFetchData", ReplyAction="urn:exportSaFetchDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestEasWindowsFormsApplication.IncServiceReference.exportSaFetchDataResponse exportSaFetchData(TestEasWindowsFormsApplication.IncServiceReference.exportSaFetchDataRequest request);
        
        // CODEGEN: Parameter 'args0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:gensabackdtl")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void gensabackdtl(TestEasWindowsFormsApplication.IncServiceReference.gensabackdtl request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportSaData", ReplyAction="urn:exportSaDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestEasWindowsFormsApplication.IncServiceReference.exportSaDataResponse exportSaData(TestEasWindowsFormsApplication.IncServiceReference.exportSaDataRequest request);
        
        // CODEGEN: Parameter 'args0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:main")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void main(TestEasWindowsFormsApplication.IncServiceReference.main request);
        
        // CODEGEN: Generating message contract since the operation exportWuliucosData is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportWuliucosData", ReplyAction="urn:exportWuliucosDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestEasWindowsFormsApplication.IncServiceReference.exportWuliucosDataResponse exportWuliucosData(TestEasWindowsFormsApplication.IncServiceReference.exportWuliucosDataRequest request);
        
        // CODEGEN: Generating message contract since the operation exportCustomersData is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportCustomersData", ReplyAction="urn:exportCustomersDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestEasWindowsFormsApplication.IncServiceReference.exportCustomersDataResponse exportCustomersData(TestEasWindowsFormsApplication.IncServiceReference.exportCustomersDataRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:doSaFetchKeepin", ReplyAction="urn:doSaFetchKeepinResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestEasWindowsFormsApplication.IncServiceReference.doSaFetchKeepinResponse doSaFetchKeepin(TestEasWindowsFormsApplication.IncServiceReference.doSaFetchKeepinRequest request);
        
        // CODEGEN: Generating message contract since the operation exportStorageDefsData is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportStorageDefsData", ReplyAction="urn:exportStorageDefsDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestEasWindowsFormsApplication.IncServiceReference.exportStorageDefsDataResponse exportStorageDefsData(TestEasWindowsFormsApplication.IncServiceReference.exportStorageDefsDataRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:doMoveout", ReplyAction="urn:doMoveoutResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestEasWindowsFormsApplication.IncServiceReference.doMoveoutResponse doMoveout(TestEasWindowsFormsApplication.IncServiceReference.doMoveoutRequest request);
        
        // CODEGEN: Generating message contract since the operation exportCompanysData is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportCompanysData", ReplyAction="urn:exportCompanysDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestEasWindowsFormsApplication.IncServiceReference.exportCompanysDataResponse exportCompanysData(TestEasWindowsFormsApplication.IncServiceReference.exportCompanysDataRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:doSaKeepin", ReplyAction="urn:doSaKeepinResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestEasWindowsFormsApplication.IncServiceReference.doSaKeepinResponse doSaKeepin(TestEasWindowsFormsApplication.IncServiceReference.doSaKeepinRequest request);
        
        // CODEGEN: Generating message contract since the operation exportEmployeesData is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportEmployeesData", ReplyAction="urn:exportEmployeesDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestEasWindowsFormsApplication.IncServiceReference.exportEmployeesDataResponse exportEmployeesData(TestEasWindowsFormsApplication.IncServiceReference.exportEmployeesDataRequest request);
        
        // CODEGEN: Generating message contract since the operation exportDicData is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportDicData", ReplyAction="urn:exportDicDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestEasWindowsFormsApplication.IncServiceReference.exportDicDataResponse exportDicData(TestEasWindowsFormsApplication.IncServiceReference.exportDicDataRequest request);
        
        // CODEGEN: Generating message contract since the operation exportPosDefsData is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportPosDefsData", ReplyAction="urn:exportPosDefsDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestEasWindowsFormsApplication.IncServiceReference.exportPosDefsDataResponse exportPosDefsData(TestEasWindowsFormsApplication.IncServiceReference.exportPosDefsDataRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:doMovein", ReplyAction="urn:doMoveinResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestEasWindowsFormsApplication.IncServiceReference.doMoveinResponse doMovein(TestEasWindowsFormsApplication.IncServiceReference.doMoveinRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportSaFetchData", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class exportSaFetchDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string args0;
        
        public exportSaFetchDataRequest() {
        }
        
        public exportSaFetchDataRequest(string args0) {
            this.args0 = args0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportSaFetchDataResponse", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class exportSaFetchDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @return;
        
        public exportSaFetchDataResponse() {
        }
        
        public exportSaFetchDataResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://control.gui.np.inca.com/xsd")]
    public partial class DBTableModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int columnCountField;
        
        private bool columnCountFieldSpecified;
        
        private bool crosstableField;
        
        private bool crosstableFieldSpecified;
        
        private object displaycolumninfosField;
        
        private bool fixtablecolumnwidthField;
        
        private bool fixtablecolumnwidthFieldSpecified;
        
        private bool hasmoreField;
        
        private bool hasmoreFieldSpecified;
        
        private bool isqueryingField;
        
        private bool isqueryingFieldSpecified;
        
        private RecordTrunk lineresultField;
        
        private object lineresultsField;
        
        private DBTableModel modifiedDataField;
        
        private string pkcolnameField;
        
        private bool queryingField;
        
        private bool queryingFieldSpecified;
        
        private DBTableModelEvent retrievelistenerField;
        
        private int rowCountField;
        
        private bool rowCountFieldSpecified;
        
        private string selectCMDField;
        
        private bool usequerythreadField;
        
        private bool usequerythreadFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int columnCount {
            get {
                return this.columnCountField;
            }
            set {
                this.columnCountField = value;
                this.RaisePropertyChanged("columnCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool columnCountSpecified {
            get {
                return this.columnCountFieldSpecified;
            }
            set {
                this.columnCountFieldSpecified = value;
                this.RaisePropertyChanged("columnCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool crosstable {
            get {
                return this.crosstableField;
            }
            set {
                this.crosstableField = value;
                this.RaisePropertyChanged("crosstable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool crosstableSpecified {
            get {
                return this.crosstableFieldSpecified;
            }
            set {
                this.crosstableFieldSpecified = value;
                this.RaisePropertyChanged("crosstableSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public object displaycolumninfos {
            get {
                return this.displaycolumninfosField;
            }
            set {
                this.displaycolumninfosField = value;
                this.RaisePropertyChanged("displaycolumninfos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool fixtablecolumnwidth {
            get {
                return this.fixtablecolumnwidthField;
            }
            set {
                this.fixtablecolumnwidthField = value;
                this.RaisePropertyChanged("fixtablecolumnwidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fixtablecolumnwidthSpecified {
            get {
                return this.fixtablecolumnwidthFieldSpecified;
            }
            set {
                this.fixtablecolumnwidthFieldSpecified = value;
                this.RaisePropertyChanged("fixtablecolumnwidthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool hasmore {
            get {
                return this.hasmoreField;
            }
            set {
                this.hasmoreField = value;
                this.RaisePropertyChanged("hasmore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hasmoreSpecified {
            get {
                return this.hasmoreFieldSpecified;
            }
            set {
                this.hasmoreFieldSpecified = value;
                this.RaisePropertyChanged("hasmoreSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool isquerying {
            get {
                return this.isqueryingField;
            }
            set {
                this.isqueryingField = value;
                this.RaisePropertyChanged("isquerying");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isqueryingSpecified {
            get {
                return this.isqueryingFieldSpecified;
            }
            set {
                this.isqueryingFieldSpecified = value;
                this.RaisePropertyChanged("isqueryingSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public RecordTrunk lineresult {
            get {
                return this.lineresultField;
            }
            set {
                this.lineresultField = value;
                this.RaisePropertyChanged("lineresult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public object lineresults {
            get {
                return this.lineresultsField;
            }
            set {
                this.lineresultsField = value;
                this.RaisePropertyChanged("lineresults");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public DBTableModel modifiedData {
            get {
                return this.modifiedDataField;
            }
            set {
                this.modifiedDataField = value;
                this.RaisePropertyChanged("modifiedData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string pkcolname {
            get {
                return this.pkcolnameField;
            }
            set {
                this.pkcolnameField = value;
                this.RaisePropertyChanged("pkcolname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public bool querying {
            get {
                return this.queryingField;
            }
            set {
                this.queryingField = value;
                this.RaisePropertyChanged("querying");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool queryingSpecified {
            get {
                return this.queryingFieldSpecified;
            }
            set {
                this.queryingFieldSpecified = value;
                this.RaisePropertyChanged("queryingSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public DBTableModelEvent retrievelistener {
            get {
                return this.retrievelistenerField;
            }
            set {
                this.retrievelistenerField = value;
                this.RaisePropertyChanged("retrievelistener");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int rowCount {
            get {
                return this.rowCountField;
            }
            set {
                this.rowCountField = value;
                this.RaisePropertyChanged("rowCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rowCountSpecified {
            get {
                return this.rowCountFieldSpecified;
            }
            set {
                this.rowCountFieldSpecified = value;
                this.RaisePropertyChanged("rowCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string selectCMD {
            get {
                return this.selectCMDField;
            }
            set {
                this.selectCMDField = value;
                this.RaisePropertyChanged("selectCMD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public bool usequerythread {
            get {
                return this.usequerythreadField;
            }
            set {
                this.usequerythreadField = value;
                this.RaisePropertyChanged("usequerythread");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usequerythreadSpecified {
            get {
                return this.usequerythreadFieldSpecified;
            }
            set {
                this.usequerythreadFieldSpecified = value;
                this.RaisePropertyChanged("usequerythreadSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://communicate.np.inca.com/xsd")]
    public partial class RecordTrunk : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dbValuesField;
        
        private int dbdeletedField;
        
        private bool dbdeletedFieldSpecified;
        
        private int dbstatusField;
        
        private bool dbstatusFieldSpecified;
        
        private DBTableModel filedbmodelField;
        
        private int grouplevelField;
        
        private bool grouplevelFieldSpecified;
        
        private string groupnameField;
        
        private string relatevalueField;
        
        private string savemessageField;
        
        private int saveresultField;
        
        private bool saveresultFieldSpecified;
        
        private int sumflagField;
        
        private bool sumflagFieldSpecified;
        
        private string tmppkidField;
        
        private object wantuploadfileField;
        
        private object wantuploadfilesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public object dbValues {
            get {
                return this.dbValuesField;
            }
            set {
                this.dbValuesField = value;
                this.RaisePropertyChanged("dbValues");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int dbdeleted {
            get {
                return this.dbdeletedField;
            }
            set {
                this.dbdeletedField = value;
                this.RaisePropertyChanged("dbdeleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dbdeletedSpecified {
            get {
                return this.dbdeletedFieldSpecified;
            }
            set {
                this.dbdeletedFieldSpecified = value;
                this.RaisePropertyChanged("dbdeletedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int dbstatus {
            get {
                return this.dbstatusField;
            }
            set {
                this.dbstatusField = value;
                this.RaisePropertyChanged("dbstatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dbstatusSpecified {
            get {
                return this.dbstatusFieldSpecified;
            }
            set {
                this.dbstatusFieldSpecified = value;
                this.RaisePropertyChanged("dbstatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public DBTableModel filedbmodel {
            get {
                return this.filedbmodelField;
            }
            set {
                this.filedbmodelField = value;
                this.RaisePropertyChanged("filedbmodel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int grouplevel {
            get {
                return this.grouplevelField;
            }
            set {
                this.grouplevelField = value;
                this.RaisePropertyChanged("grouplevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grouplevelSpecified {
            get {
                return this.grouplevelFieldSpecified;
            }
            set {
                this.grouplevelFieldSpecified = value;
                this.RaisePropertyChanged("grouplevelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string groupname {
            get {
                return this.groupnameField;
            }
            set {
                this.groupnameField = value;
                this.RaisePropertyChanged("groupname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string relatevalue {
            get {
                return this.relatevalueField;
            }
            set {
                this.relatevalueField = value;
                this.RaisePropertyChanged("relatevalue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string savemessage {
            get {
                return this.savemessageField;
            }
            set {
                this.savemessageField = value;
                this.RaisePropertyChanged("savemessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int saveresult {
            get {
                return this.saveresultField;
            }
            set {
                this.saveresultField = value;
                this.RaisePropertyChanged("saveresult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool saveresultSpecified {
            get {
                return this.saveresultFieldSpecified;
            }
            set {
                this.saveresultFieldSpecified = value;
                this.RaisePropertyChanged("saveresultSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int sumflag {
            get {
                return this.sumflagField;
            }
            set {
                this.sumflagField = value;
                this.RaisePropertyChanged("sumflag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sumflagSpecified {
            get {
                return this.sumflagFieldSpecified;
            }
            set {
                this.sumflagFieldSpecified = value;
                this.RaisePropertyChanged("sumflagSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string tmppkid {
            get {
                return this.tmppkidField;
            }
            set {
                this.tmppkidField = value;
                this.RaisePropertyChanged("tmppkid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public object wantuploadfile {
            get {
                return this.wantuploadfileField;
            }
            set {
                this.wantuploadfileField = value;
                this.RaisePropertyChanged("wantuploadfile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public object wantuploadfiles {
            get {
                return this.wantuploadfilesField;
            }
            set {
                this.wantuploadfilesField = value;
                this.RaisePropertyChanged("wantuploadfiles");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://control.gui.np.inca.com/xsd")]
    public partial class DBTableModelEvent : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gensabackdtl", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class gensabackdtl {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("args0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public TestEasWindowsFormsApplication.IncServiceReference.DBTableModel args1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public TestEasWindowsFormsApplication.IncServiceReference.DBTableModel args2;
        
        public gensabackdtl() {
        }
        
        public gensabackdtl(int[] args0, TestEasWindowsFormsApplication.IncServiceReference.DBTableModel args1, TestEasWindowsFormsApplication.IncServiceReference.DBTableModel args2) {
            this.args0 = args0;
            this.args1 = args1;
            this.args2 = args2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportSaData", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class exportSaDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string args0;
        
        public exportSaDataRequest() {
        }
        
        public exportSaDataRequest(string args0) {
            this.args0 = args0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportSaDataResponse", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class exportSaDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @return;
        
        public exportSaDataResponse() {
        }
        
        public exportSaDataResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="main", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class main {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("args0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] args0;
        
        public main() {
        }
        
        public main(string[] args0) {
            this.args0 = args0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exportWuliucosDataRequest {
        
        public exportWuliucosDataRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportWuliucosDataResponse", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class exportWuliucosDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @return;
        
        public exportWuliucosDataResponse() {
        }
        
        public exportWuliucosDataResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exportCustomersDataRequest {
        
        public exportCustomersDataRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportCustomersDataResponse", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class exportCustomersDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @return;
        
        public exportCustomersDataResponse() {
        }
        
        public exportCustomersDataResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doSaFetchKeepin", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class doSaFetchKeepinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string args0;
        
        public doSaFetchKeepinRequest() {
        }
        
        public doSaFetchKeepinRequest(string args0) {
            this.args0 = args0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doSaFetchKeepinResponse", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class doSaFetchKeepinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @return;
        
        public doSaFetchKeepinResponse() {
        }
        
        public doSaFetchKeepinResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exportStorageDefsDataRequest {
        
        public exportStorageDefsDataRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportStorageDefsDataResponse", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class exportStorageDefsDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @return;
        
        public exportStorageDefsDataResponse() {
        }
        
        public exportStorageDefsDataResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doMoveout", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class doMoveoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string args0;
        
        public doMoveoutRequest() {
        }
        
        public doMoveoutRequest(string args0) {
            this.args0 = args0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doMoveoutResponse", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class doMoveoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @return;
        
        public doMoveoutResponse() {
        }
        
        public doMoveoutResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exportCompanysDataRequest {
        
        public exportCompanysDataRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportCompanysDataResponse", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class exportCompanysDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @return;
        
        public exportCompanysDataResponse() {
        }
        
        public exportCompanysDataResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doSaKeepin", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class doSaKeepinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string args0;
        
        public doSaKeepinRequest() {
        }
        
        public doSaKeepinRequest(string args0) {
            this.args0 = args0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doSaKeepinResponse", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class doSaKeepinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @return;
        
        public doSaKeepinResponse() {
        }
        
        public doSaKeepinResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exportEmployeesDataRequest {
        
        public exportEmployeesDataRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportEmployeesDataResponse", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class exportEmployeesDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @return;
        
        public exportEmployeesDataResponse() {
        }
        
        public exportEmployeesDataResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exportDicDataRequest {
        
        public exportDicDataRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportDicDataResponse", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class exportDicDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @return;
        
        public exportDicDataResponse() {
        }
        
        public exportDicDataResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exportPosDefsDataRequest {
        
        public exportPosDefsDataRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportPosDefsDataResponse", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class exportPosDefsDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @return;
        
        public exportPosDefsDataResponse() {
        }
        
        public exportPosDefsDataResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doMovein", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class doMoveinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string args0;
        
        public doMoveinRequest() {
        }
        
        public doMoveinRequest(string args0) {
            this.args0 = args0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doMoveinResponse", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class doMoveinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @return;
        
        public doMoveinResponse() {
        }
        
        public doMoveinResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicePortTypeChannel : TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicePortTypeClient : System.ServiceModel.ClientBase<TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType>, TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType {
        
        public WebServicePortTypeClient() {
        }
        
        public WebServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestEasWindowsFormsApplication.IncServiceReference.exportSaFetchDataResponse TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType.exportSaFetchData(TestEasWindowsFormsApplication.IncServiceReference.exportSaFetchDataRequest request) {
            return base.Channel.exportSaFetchData(request);
        }
        
        public string exportSaFetchData(string args0) {
            TestEasWindowsFormsApplication.IncServiceReference.exportSaFetchDataRequest inValue = new TestEasWindowsFormsApplication.IncServiceReference.exportSaFetchDataRequest();
            inValue.args0 = args0;
            TestEasWindowsFormsApplication.IncServiceReference.exportSaFetchDataResponse retVal = ((TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType)(this)).exportSaFetchData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType.gensabackdtl(TestEasWindowsFormsApplication.IncServiceReference.gensabackdtl request) {
            base.Channel.gensabackdtl(request);
        }
        
        public void gensabackdtl(int[] args0, TestEasWindowsFormsApplication.IncServiceReference.DBTableModel args1, TestEasWindowsFormsApplication.IncServiceReference.DBTableModel args2) {
            TestEasWindowsFormsApplication.IncServiceReference.gensabackdtl inValue = new TestEasWindowsFormsApplication.IncServiceReference.gensabackdtl();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            ((TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType)(this)).gensabackdtl(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestEasWindowsFormsApplication.IncServiceReference.exportSaDataResponse TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType.exportSaData(TestEasWindowsFormsApplication.IncServiceReference.exportSaDataRequest request) {
            return base.Channel.exportSaData(request);
        }
        
        public string exportSaData(string args0) {
            TestEasWindowsFormsApplication.IncServiceReference.exportSaDataRequest inValue = new TestEasWindowsFormsApplication.IncServiceReference.exportSaDataRequest();
            inValue.args0 = args0;
            TestEasWindowsFormsApplication.IncServiceReference.exportSaDataResponse retVal = ((TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType)(this)).exportSaData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType.main(TestEasWindowsFormsApplication.IncServiceReference.main request) {
            base.Channel.main(request);
        }
        
        public void main(string[] args0) {
            TestEasWindowsFormsApplication.IncServiceReference.main inValue = new TestEasWindowsFormsApplication.IncServiceReference.main();
            inValue.args0 = args0;
            ((TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType)(this)).main(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestEasWindowsFormsApplication.IncServiceReference.exportWuliucosDataResponse TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType.exportWuliucosData(TestEasWindowsFormsApplication.IncServiceReference.exportWuliucosDataRequest request) {
            return base.Channel.exportWuliucosData(request);
        }
        
        public string exportWuliucosData() {
            TestEasWindowsFormsApplication.IncServiceReference.exportWuliucosDataRequest inValue = new TestEasWindowsFormsApplication.IncServiceReference.exportWuliucosDataRequest();
            TestEasWindowsFormsApplication.IncServiceReference.exportWuliucosDataResponse retVal = ((TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType)(this)).exportWuliucosData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestEasWindowsFormsApplication.IncServiceReference.exportCustomersDataResponse TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType.exportCustomersData(TestEasWindowsFormsApplication.IncServiceReference.exportCustomersDataRequest request) {
            return base.Channel.exportCustomersData(request);
        }
        
        public string exportCustomersData() {
            TestEasWindowsFormsApplication.IncServiceReference.exportCustomersDataRequest inValue = new TestEasWindowsFormsApplication.IncServiceReference.exportCustomersDataRequest();
            TestEasWindowsFormsApplication.IncServiceReference.exportCustomersDataResponse retVal = ((TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType)(this)).exportCustomersData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestEasWindowsFormsApplication.IncServiceReference.doSaFetchKeepinResponse TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType.doSaFetchKeepin(TestEasWindowsFormsApplication.IncServiceReference.doSaFetchKeepinRequest request) {
            return base.Channel.doSaFetchKeepin(request);
        }
        
        public string doSaFetchKeepin(string args0) {
            TestEasWindowsFormsApplication.IncServiceReference.doSaFetchKeepinRequest inValue = new TestEasWindowsFormsApplication.IncServiceReference.doSaFetchKeepinRequest();
            inValue.args0 = args0;
            TestEasWindowsFormsApplication.IncServiceReference.doSaFetchKeepinResponse retVal = ((TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType)(this)).doSaFetchKeepin(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestEasWindowsFormsApplication.IncServiceReference.exportStorageDefsDataResponse TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType.exportStorageDefsData(TestEasWindowsFormsApplication.IncServiceReference.exportStorageDefsDataRequest request) {
            return base.Channel.exportStorageDefsData(request);
        }
        
        public string exportStorageDefsData() {
            TestEasWindowsFormsApplication.IncServiceReference.exportStorageDefsDataRequest inValue = new TestEasWindowsFormsApplication.IncServiceReference.exportStorageDefsDataRequest();
            TestEasWindowsFormsApplication.IncServiceReference.exportStorageDefsDataResponse retVal = ((TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType)(this)).exportStorageDefsData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestEasWindowsFormsApplication.IncServiceReference.doMoveoutResponse TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType.doMoveout(TestEasWindowsFormsApplication.IncServiceReference.doMoveoutRequest request) {
            return base.Channel.doMoveout(request);
        }
        
        public string doMoveout(string args0) {
            TestEasWindowsFormsApplication.IncServiceReference.doMoveoutRequest inValue = new TestEasWindowsFormsApplication.IncServiceReference.doMoveoutRequest();
            inValue.args0 = args0;
            TestEasWindowsFormsApplication.IncServiceReference.doMoveoutResponse retVal = ((TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType)(this)).doMoveout(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestEasWindowsFormsApplication.IncServiceReference.exportCompanysDataResponse TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType.exportCompanysData(TestEasWindowsFormsApplication.IncServiceReference.exportCompanysDataRequest request) {
            return base.Channel.exportCompanysData(request);
        }
        
        public string exportCompanysData() {
            TestEasWindowsFormsApplication.IncServiceReference.exportCompanysDataRequest inValue = new TestEasWindowsFormsApplication.IncServiceReference.exportCompanysDataRequest();
            TestEasWindowsFormsApplication.IncServiceReference.exportCompanysDataResponse retVal = ((TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType)(this)).exportCompanysData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestEasWindowsFormsApplication.IncServiceReference.doSaKeepinResponse TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType.doSaKeepin(TestEasWindowsFormsApplication.IncServiceReference.doSaKeepinRequest request) {
            return base.Channel.doSaKeepin(request);
        }
        
        public string doSaKeepin(string args0) {
            TestEasWindowsFormsApplication.IncServiceReference.doSaKeepinRequest inValue = new TestEasWindowsFormsApplication.IncServiceReference.doSaKeepinRequest();
            inValue.args0 = args0;
            TestEasWindowsFormsApplication.IncServiceReference.doSaKeepinResponse retVal = ((TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType)(this)).doSaKeepin(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestEasWindowsFormsApplication.IncServiceReference.exportEmployeesDataResponse TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType.exportEmployeesData(TestEasWindowsFormsApplication.IncServiceReference.exportEmployeesDataRequest request) {
            return base.Channel.exportEmployeesData(request);
        }
        
        public string exportEmployeesData() {
            TestEasWindowsFormsApplication.IncServiceReference.exportEmployeesDataRequest inValue = new TestEasWindowsFormsApplication.IncServiceReference.exportEmployeesDataRequest();
            TestEasWindowsFormsApplication.IncServiceReference.exportEmployeesDataResponse retVal = ((TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType)(this)).exportEmployeesData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestEasWindowsFormsApplication.IncServiceReference.exportDicDataResponse TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType.exportDicData(TestEasWindowsFormsApplication.IncServiceReference.exportDicDataRequest request) {
            return base.Channel.exportDicData(request);
        }
        
        public string exportDicData() {
            TestEasWindowsFormsApplication.IncServiceReference.exportDicDataRequest inValue = new TestEasWindowsFormsApplication.IncServiceReference.exportDicDataRequest();
            TestEasWindowsFormsApplication.IncServiceReference.exportDicDataResponse retVal = ((TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType)(this)).exportDicData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestEasWindowsFormsApplication.IncServiceReference.exportPosDefsDataResponse TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType.exportPosDefsData(TestEasWindowsFormsApplication.IncServiceReference.exportPosDefsDataRequest request) {
            return base.Channel.exportPosDefsData(request);
        }
        
        public string exportPosDefsData() {
            TestEasWindowsFormsApplication.IncServiceReference.exportPosDefsDataRequest inValue = new TestEasWindowsFormsApplication.IncServiceReference.exportPosDefsDataRequest();
            TestEasWindowsFormsApplication.IncServiceReference.exportPosDefsDataResponse retVal = ((TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType)(this)).exportPosDefsData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestEasWindowsFormsApplication.IncServiceReference.doMoveinResponse TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType.doMovein(TestEasWindowsFormsApplication.IncServiceReference.doMoveinRequest request) {
            return base.Channel.doMovein(request);
        }
        
        public string doMovein(string args0) {
            TestEasWindowsFormsApplication.IncServiceReference.doMoveinRequest inValue = new TestEasWindowsFormsApplication.IncServiceReference.doMoveinRequest();
            inValue.args0 = args0;
            TestEasWindowsFormsApplication.IncServiceReference.doMoveinResponse retVal = ((TestEasWindowsFormsApplication.IncServiceReference.WebServicePortType)(this)).doMovein(inValue);
            return retVal.@return;
        }
    }
}
