//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestInvockWebServiceConsoleApp.WcsWebServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webServiceI.ewms.zjepe.com", ConfigurationName="WcsWebServiceReference.WcsWebServiceSoap")]
    public interface WcsWebServiceSoap {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://webServiceI.ewms.zjepe.com/) of message XMZ_WCS_SUCCESSRequest does not match the default value (http://webServiceI.ewms.zjepe.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceI.ewms.zjepe.com/XMZ_WCS_SUCCESS", ReplyAction="*")]
        TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_SUCCESSResponse XMZ_WCS_SUCCESS(TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_SUCCESSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceI.ewms.zjepe.com/XMZ_WCS_SUCCESS", ReplyAction="*")]
        System.Threading.Tasks.Task<TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_SUCCESSResponse> XMZ_WCS_SUCCESSAsync(TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_SUCCESSRequest request);
        
        // CODEGEN: Generating message contract since element name AUTO_TYPE from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceI.ewms.zjepe.com/XMZ_WCS_COMMAND", ReplyAction="*")]
        TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_COMMANDResponse XMZ_WCS_COMMAND(TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_COMMANDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServiceI.ewms.zjepe.com/XMZ_WCS_COMMAND", ReplyAction="*")]
        System.Threading.Tasks.Task<TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_COMMANDResponse> XMZ_WCS_COMMANDAsync(TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_COMMANDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="XMZ_WCS_SUCCESS", WrapperNamespace="http://webServiceI.ewms.zjepe.com/", IsWrapped=true)]
    public partial class XMZ_WCS_SUCCESSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string AUTO_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string IS_SUCCESS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string AUTO_TYPE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string IS_FINISH;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string WHSE_ID;
        
        public XMZ_WCS_SUCCESSRequest() {
        }
        
        public XMZ_WCS_SUCCESSRequest(string AUTO_ID, string IS_SUCCESS, string AUTO_TYPE, string IS_FINISH, string WHSE_ID) {
            this.AUTO_ID = AUTO_ID;
            this.IS_SUCCESS = IS_SUCCESS;
            this.AUTO_TYPE = AUTO_TYPE;
            this.IS_FINISH = IS_FINISH;
            this.WHSE_ID = WHSE_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="XMZ_WCS_SUCCESSResponse", WrapperNamespace="http://webServiceI.ewms.zjepe.com/", IsWrapped=true)]
    public partial class XMZ_WCS_SUCCESSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public XMZ_WCS_SUCCESSResponse() {
        }
        
        public XMZ_WCS_SUCCESSResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XMZ_WCS_COMMANDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XMZ_WCS_COMMAND", Namespace="http://webServiceI.ewms.zjepe.com", Order=0)]
        public TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_COMMANDRequestBody Body;
        
        public XMZ_WCS_COMMANDRequest() {
        }
        
        public XMZ_WCS_COMMANDRequest(TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_COMMANDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class XMZ_WCS_COMMANDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AUTO_TYPE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string WHSE_ID;
        
        public XMZ_WCS_COMMANDRequestBody() {
        }
        
        public XMZ_WCS_COMMANDRequestBody(string AUTO_TYPE, string WHSE_ID) {
            this.AUTO_TYPE = AUTO_TYPE;
            this.WHSE_ID = WHSE_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XMZ_WCS_COMMANDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XMZ_WCS_COMMANDResponse", Namespace="http://webServiceI.ewms.zjepe.com", Order=0)]
        public TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_COMMANDResponseBody Body;
        
        public XMZ_WCS_COMMANDResponse() {
        }
        
        public XMZ_WCS_COMMANDResponse(TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_COMMANDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class XMZ_WCS_COMMANDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public XMZ_WCS_COMMANDResponseBody() {
        }
        
        public XMZ_WCS_COMMANDResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WcsWebServiceSoapChannel : TestInvockWebServiceConsoleApp.WcsWebServiceReference.WcsWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcsWebServiceSoapClient : System.ServiceModel.ClientBase<TestInvockWebServiceConsoleApp.WcsWebServiceReference.WcsWebServiceSoap>, TestInvockWebServiceConsoleApp.WcsWebServiceReference.WcsWebServiceSoap {
        
        public WcsWebServiceSoapClient() {
        }
        
        public WcsWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcsWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcsWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcsWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_SUCCESSResponse TestInvockWebServiceConsoleApp.WcsWebServiceReference.WcsWebServiceSoap.XMZ_WCS_SUCCESS(TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_SUCCESSRequest request) {
            return base.Channel.XMZ_WCS_SUCCESS(request);
        }
        
        public string XMZ_WCS_SUCCESS(string AUTO_ID, string IS_SUCCESS, string AUTO_TYPE, string IS_FINISH, string WHSE_ID) {
            TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_SUCCESSRequest inValue = new TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_SUCCESSRequest();
            inValue.AUTO_ID = AUTO_ID;
            inValue.IS_SUCCESS = IS_SUCCESS;
            inValue.AUTO_TYPE = AUTO_TYPE;
            inValue.IS_FINISH = IS_FINISH;
            inValue.WHSE_ID = WHSE_ID;
            TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_SUCCESSResponse retVal = ((TestInvockWebServiceConsoleApp.WcsWebServiceReference.WcsWebServiceSoap)(this)).XMZ_WCS_SUCCESS(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_SUCCESSResponse> TestInvockWebServiceConsoleApp.WcsWebServiceReference.WcsWebServiceSoap.XMZ_WCS_SUCCESSAsync(TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_SUCCESSRequest request) {
            return base.Channel.XMZ_WCS_SUCCESSAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_SUCCESSResponse> XMZ_WCS_SUCCESSAsync(string AUTO_ID, string IS_SUCCESS, string AUTO_TYPE, string IS_FINISH, string WHSE_ID) {
            TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_SUCCESSRequest inValue = new TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_SUCCESSRequest();
            inValue.AUTO_ID = AUTO_ID;
            inValue.IS_SUCCESS = IS_SUCCESS;
            inValue.AUTO_TYPE = AUTO_TYPE;
            inValue.IS_FINISH = IS_FINISH;
            inValue.WHSE_ID = WHSE_ID;
            return ((TestInvockWebServiceConsoleApp.WcsWebServiceReference.WcsWebServiceSoap)(this)).XMZ_WCS_SUCCESSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_COMMANDResponse TestInvockWebServiceConsoleApp.WcsWebServiceReference.WcsWebServiceSoap.XMZ_WCS_COMMAND(TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_COMMANDRequest request) {
            return base.Channel.XMZ_WCS_COMMAND(request);
        }
        
        public string XMZ_WCS_COMMAND(string AUTO_TYPE, string WHSE_ID) {
            TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_COMMANDRequest inValue = new TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_COMMANDRequest();
            inValue.Body = new TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_COMMANDRequestBody();
            inValue.Body.AUTO_TYPE = AUTO_TYPE;
            inValue.Body.WHSE_ID = WHSE_ID;
            TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_COMMANDResponse retVal = ((TestInvockWebServiceConsoleApp.WcsWebServiceReference.WcsWebServiceSoap)(this)).XMZ_WCS_COMMAND(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_COMMANDResponse> TestInvockWebServiceConsoleApp.WcsWebServiceReference.WcsWebServiceSoap.XMZ_WCS_COMMANDAsync(TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_COMMANDRequest request) {
            return base.Channel.XMZ_WCS_COMMANDAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_COMMANDResponse> XMZ_WCS_COMMANDAsync(string AUTO_TYPE, string WHSE_ID) {
            TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_COMMANDRequest inValue = new TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_COMMANDRequest();
            inValue.Body = new TestInvockWebServiceConsoleApp.WcsWebServiceReference.XMZ_WCS_COMMANDRequestBody();
            inValue.Body.AUTO_TYPE = AUTO_TYPE;
            inValue.Body.WHSE_ID = WHSE_ID;
            return ((TestInvockWebServiceConsoleApp.WcsWebServiceReference.WcsWebServiceSoap)(this)).XMZ_WCS_COMMANDAsync(inValue);
        }
    }
}
